-- PARAMS:
-- (khong co tham so)


 CREATE PROC [dbo].[HR_NHANVIEN2_GETALL5]
 AS
 BEGIN
	SELECT A.MANV, A.HOTEN, A.HOTEN_EN, A.NGAYSINH, A.NGAYVAOLAM,
		A.DANGHIVIEC, A.LYDOTHOIVIEC, A.NGAYNGHIVIEC, A.NGAYNOPDON,
		A.MACHAMCONG, 
		A.BOPHAN, B.TENBOPHAN, 
		A.MACONGTY, C.TenCty, 
		A.CALAMVIEC, D.chucvu,
		A.MACONGDOAN, OP.n_op AS TENCONGDOAN
	FROM hr_nhanvien_2 A
		INNER JOIN hr_bophan_2 B ON A.BOPHAN = B.ID
		LEFT JOIN hr_congty C ON A.MACONGTY = C.MaCty
		LEFT JOIN tr_chucvu D ON A.MACHUCVU COLLATE SQL_Latin1_General_CP1_CI_AI = D.machucvu COLLATE SQL_Latin1_General_CP1_CI_AI
		LEFT JOIN trtb_m_op OP ON A.MACONGDOAN = OP.c_op
	WHERE A.DANGHIVIEC = 'N'
		AND A.BOPHAN IN ('DINHHINH', 'HANGTRANG', 'HOANTHIEN', 'LAPRAP', 'LR.TRUOCSON', 'NGUOI', 'PHOI', 'SON', 'THANHPHAM')
END

