-- PARAMS:
-- @ID int
-- @SOLUONG decimal


CREATE PROC [dbo].[TR_DONDATHANG_CHITIET_NHAP]
(
	@ID INT,
	@SOLUONG DECIMAL(18,2)
)
AS

DECLARE @SOLUONG_DAT DECIMAL(18,2);
DECLARE @SOLUONG_DANHAN DECIMAL(18,2);
DECLARE @SOLUONG_CONLAI DECIMAL(18,2);

SELECT @SOLUONG_DAT = soluong,
	@SOLUONG_CONLAI = sl_conlai,
	@SOLUONG_DANHAN = sl_danhan
FROM tr_dondathang_chitiet
WHERE ID = @ID

SET @SOLUONG_DANHAN = @SOLUONG_DANHAN + @SOLUONG;
SET @SOLUONG_CONLAI = @SOLUONG_DAT - @SOLUONG_DANHAN;

IF @SOLUONG_CONLAI < 0
	SET @SOLUONG_CONLAI = 0

UPDATE tr_dondathang_chitiet
SET sl_conlai = @SOLUONG_CONLAI,
	sl_danhan = @SOLUONG_DANHAN
WHERE id = @ID;


