-- PARAMS:
-- @OrderNumber nvarchar

CREATE PROC [dbo].[TR_ORDER_GetByOrder] (@OrderNumber NVARCHAR (200))
AS
BEGIN
   SELECT a.id,
          a.customer,
          a.agent,
          [range] = CASE WHEN ISNULL (a.[range], '') = '' THEN b.hehang ELSE a.[range] END,
          a.order_number,
          a.item_number,
          cust_item_number = CASE WHEN ISNULL (a.cust_item_number, '') = '' THEN b.masp_khachhang ELSE a.cust_item_number END,
          b.mausac AS 'color',
          b.tensp AS 'description',
          b.tensp_vn,
          c.chitiet,
          material = B.nguyenlieu,
		  A.tenkhoahoc,
          order_qty = AVG (a.order_qty),AVG (CAST (b.cbm AS DECIMAL (18, 3))) cbm,
          dongia = AVG (c.dongia),
          price = AVG (IIF (a.price = 0, B.dongia, a.price)),
          currency = IIF (ISNULL (a.currency, '') = '', B.loaitien, a.currency),
          amount = AVG (a.amount),
          a.bill_to,
          a.ship_to,
          a.destination_port,
          a.etd,
          a.ship_date,
          ship_qty = AVG (a.ship_qty),
          input_qty = AVG (a.input_qty),
          a.order_date,
          a.cont_date,
          a.container_size,
          a.nccht,
          a.payment_term,
          a.remark,
          a.cust_po_number,
          a.attribute4,
          a.choduyet,
          a.f_cancelled,
          a.Finished,
          a.create_by,
          a.create_date,
          a.update_by,
          a.update_date,
          b.m3,
          b.masp_khachhang,
          b.tensp,
          b.IsBaoBi,
          b.IsGoVan,
          b.IsNguKim,
          b.IsSon,
		  a.fsc_100, a.fsc_cw, a.fsc_mix, a.fsc_recycled,
		  SUM(DISTINCT b.n_weight) AS n_weight, 
		  SUM(DISTINCT b.g_weight) AS g_weight
   FROM tr_order_detail a
        LEFT JOIN tr_sanpham b ON a.item_number = b.masp
        LEFT JOIN
        (SELECT DISTINCT dh.maddh,
                         ct.masp,
                         ct.chitiet,
                         ct.dongia,
                         dh.donhang
         FROM tr_dondathang_chitiet ct
              INNER JOIN tr_dondathang dh ON ct.maddh = dh.maddh
         WHERE ct.chitiet LIKE 'W%' AND dh.active = 1 AND dh.pheduyet = '1')
        c
           ON     a.item_number = c.masp
              AND CHARINDEX (a.order_number, c.donhang) > 0
   WHERE order_number = @OrderNumber AND f_cancelled = 'N'
   GROUP BY a.id,
            a.customer,
            a.agent,
            a.[range],
            b.hehang,
            a.order_number,
            a.item_number,
            a.cust_item_number,
            b.masp_khachhang,
            --a.description,a.color,
            c.chitiet,
            --a.material,
            b.nguyenlieu,
			A.tenkhoahoc,
            IIF (ISNULL (a.currency, '') = '', B.loaitien, a.currency),
            a.bill_to,
            a.ship_to,
            a.destination_port,
            a.etd,
            a.ship_date,
            a.order_date,
            a.cont_date,
            a.container_size,
            a.nccht,
            a.payment_term,
            a.remark,
            a.cust_po_number,
            a.attribute4,
            a.choduyet,
            a.f_cancelled,
            a.Finished,
            a.create_by,
            a.create_date,
            a.update_by,
            a.update_date,
            b.m3,
            b.masp_khachhang,
            b.tensp,
            b.IsBaoBi,
            b.IsGoVan,
            b.IsNguKim,
            b.IsSon,
			a.fsc_100, a.fsc_cw, a.fsc_mix, a.fsc_recycled,
            b.mausac,
            b.tensp_vn,
            b.tensp
END
