-- PARAMS:
-- (khong co tham so)

CREATE PROC [dbo].[TR_SANPHAM_GetAll2]
AS
BEGIN
SELECT A.id,
       A.masp,
       A.masp_khachhang,
       A.masp_nhamay,
       A.tensp,
       A.tensp_vn,
       A.hehang,
       A.mausac,
       A.mauuv,
       A.loaisp, B.tenloaisp,
       A.ketcau,
       A.bemat_sanpham,
       A.ghichu,
       A.dai,
       A.rong,
       A.cao,
       A.kichthuoc,
       A.nguyenlieu,
       A.dvt,
       A.quycach,
       A.m2,
       A.m3,
       A.dai_carton,
       A.rong_carton,
       A.cao_carton,
       a.quycach_carton,
	   CAST (A.cbm AS float) AS cbm,
       CAST (A.cbm * 35.315 AS float) AS cuft,
       A.carton_qty,
       A.dongia,
       A.loaitien,
       A.vendor,
       A.customer,
       E.customer_name,
       A.dacdiem,
       A.hinhanh,
       NULL hinhanh1,
       NULL thumbnail,
       A.IsGoVan,
       A.IsNguKim,
       A.IsSon,
       A.IsBaoBi,
       A.IsHangTrang,
       A.banve,
       A.ngaybaogia,
       A.hanbaogia,
       A.create_by,
       A.create_date,
       A.update_by,
       A.update_date,
       NULL hinhanh2,
       A.heso_mam,
       A.dongia_mam,
       A.active,
       A.n_weight,
       A.g_weight,
       A.ThoiDiem,
       A.ma_btp,
       A.ma_erp,
	   A.IsASTM,
	   A.mautrong,
	   A.mauStaincanh,
	   A.tieuchuan,
	   A.sothung_carton,
	   A.tieuchuan_carton,
	   A.solop_carton,
	   A.dobuc_carton,
	   A.nguyenlieu_vatchen,
	   A.dinhluong_vatchen,
	   A.tuichongdo,
	   A.droptest,
	   A.interlock,
	   A.tiptest,
	   dongia_son = ISNULL(A.dongia_son, D.dongia),
	   A.isCreatedCosting, A.m3_tc, A.oast_date
FROM tr_sanpham A
	LEFT JOIN tr_loaisp B ON A.loaisp = B.maloaisp
	LEFT JOIN tr_color D ON A.mausac = D.code
	LEFT JOIN tr_khachhang E ON A.customer = E.customer_id
WHERE A.active = 0 AND ISNULL (tensp, '') <> ''
END
